"""``make report``: results/report.md and the README's generated block, from committed JSON.

No number in the README's first screen is typed by hand (docs/PLAN.md AC8).
Everything between ``BEGIN`` and ``END`` in README.md is rewritten from:
``results/analysis/{summary,haiku}.json``, ``results/llm/haiku-8way.json``,
``results/efficiency/*.json``, ``results/cost/cost.json``, the curve indexes,
the pilots and the run JSONs. ``--check`` rewrites nothing and exits 1 when
either file differs from what the JSON gives; tests/test_report.py runs the
same comparison in CI.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from tinyrouter.cost import training_runs

BEGIN = "<!-- BEGIN GENERATED by `make report` from results/*.json; do not edit by hand -->"
END = "<!-- END GENERATED -->"
TARGET = "0.02"
MODEL_LABEL = {"bert": "BERT-base", "modernbert": "ModernBERT-base"}
FIGURES = (
    (
        "learning_curves.png",
        "Learning curves",
        "Test 8-way accuracy and OOS recall against labelled examples per intent (log scale), "
        "small model alone, 8-way aggregation chosen on validation; bands are mean ± std over "
        "three seeds. The dash-dot line is Claude Haiku 4.5 zero-shot on the same queries. "
        "Shaded: k ≤ 10 trains for the fixed 400-step budget.",
    ),
    (
        "risk_coverage.png",
        "Risk-coverage",
        "Test selective risk (8-way error among the queries the small model keeps) against "
        "coverage, for ModernBERT at k=10 and k=100, for each confidence signal; the band is "
        "the std of the temperature-scaled MSP, the main signal. The four signals nearly "
        "coincide.",
    ),
    (
        "routers.png",
        "Router comparison",
        "Test 8-way accuracy (a) and share of queries sent to Haiku (b) for LLM-only, "
        "small-only, the hybrid (threshold chosen on validation for 2% selective risk) and the "
        "oracle, which defers exactly the small model's errors. Panel (a) uses points, not "
        "bars, and its axis starts at 75%, so vertical distance is the difference in accuracy "
        "points and nothing is read from bar length; panel (b) starts at 0. Error bars are std "
        "over three seeds.",
    ),
    (
        "threshold_transfer.png",
        "Threshold transfer",
        "Selective risk of the hybrid whose threshold was chosen on validation for 2% risk: on "
        "validation, on test, and on test reweighted to the validation OOS share (a diagnostic, "
        "not a method). Points appear where all three seeds had a feasible threshold.",
    ),
)


@dataclass(frozen=True)
class Results:
    summary: dict
    haiku: dict
    llm: dict
    cpu: dict
    haiku_latency: dict
    cost: dict
    indexes: dict[str, dict]
    pilots: dict[str, dict]
    k100_training: dict[str, list[dict]]

    @classmethod
    def load(cls, root: Path) -> Results:
        def read(name: str) -> dict:
            return json.loads((root / name).read_text(encoding="utf-8"))

        return cls(
            summary=read("analysis/summary.json"),
            haiku=read("analysis/haiku.json"),
            llm=read("llm/haiku-8way.json"),
            cpu=read("efficiency/cpu_latency.json"),
            haiku_latency=read("efficiency/haiku_latency.json"),
            cost=read("cost/cost.json"),
            indexes={m: read(f"curves/{m}.json") for m in MODEL_LABEL},
            pilots={p: read(f"pilots/{p}.json") for p in ("lr", "steps")},
            k100_training={m: training_runs(root, m)[100] for m in MODEL_LABEL},
        )

    def group(self, name: str) -> dict:
        return self.summary["groups"][name]["result"]

    def hybrid(self, name: str) -> dict:
        return self.group(name)["final"]["fallback"][TARGET]["hybrid"]

    @property
    def test_n(self) -> int:
        return int(self.summary["llm_only_test"]["n"])


def pct(value: float, digits: int = 1) -> str:
    return f"{100 * value:.{digits}f}"


def pm(stat: dict, digits: int = 1, scale: float = 100.0) -> str:
    """``mean ± std`` of a combined statistic; std shown only when there is one."""
    mean = f"{scale * stat['mean']:.{digits}f}"
    if stat.get("std") is None:
        return mean
    return f"{mean} ± {scale * stat['std']:.{digits}f}"


def usd(value: float, digits: int = 3) -> str:
    return f"US${value:,.{digits}f}"


def queries(value: float | None) -> str:
    return "never" if value is None else f"{value:,.0f}"


def headline(r: Results) -> list[str]:
    main = r.group("modernbert/k100")
    small10 = r.group("modernbert/k10")["final"]["small_only"]
    hybrid10 = r.hybrid("modernbert/k10")["test"]
    diag = main["diagnostics"][TARGET]
    haiku = r.summary["llm_only_test"]
    target = pct(float(TARGET), 0)
    transferred = (
        f"ModernBERT-base fine-tuned on all 100 examples per intent routes "
        f"{pm(main['final']['small_only']['accuracy_8'])}% of test queries correctly in the "
        f"8-way space (Claude Haiku 4.5 zero-shot: {pct(haiku['accuracy_8'])}%).",
        f"With 10 examples per intent, deferring low-confidence queries to Haiku lifts 8-way "
        f"accuracy from {pm(small10['accuracy_8'])}% (small model alone) to "
        f"{pm(hybrid10['accuracy_8'])}%, with Haiku called on "
        f"{pm(hybrid10['llm_call_rate'])}% of queries "
        f"({call_counts(hybrid10['llm_call_rate'], r.test_n)} for seeds 42, 43, 44).",
    )
    missed = (
        f"The deferral threshold chosen on validation for {target}% selective risk gives "
        f"{pm(diag['test']['selective_risk'], 2)}% selective risk on test (ModernBERT k=100; "
        f"validation: {pm(diag['validation']['selective_risk'], 2)}%).",
        f"Validation is {pct(diag['validation_oos_share']['mean'])}% OOS and test "
        f"{pct(diag['test_oos_share']['mean'])}%. In a reweighting diagnostic, weighting test to "
        f"the validation OOS share closes about "
        f"{round(100 * diag['share_of_gap_explained_by_oos_share']['mean'])}% of the gap between "
        f"validation and test risk; the remaining difference is consistent with a higher "
        f"conditional error rate "
        f"on test OOS queries that the model keeps ({pm(diag['test']['kept_oos_error_rate'])}% "
        f"vs {pm(diag['validation']['kept_oos_error_rate'])}% on validation).",
    )
    return [
        "Test split, 8-way routing (7 agents + out-of-scope), mean ± std over seeds 42, 43, 44.",
        "",
        "| What transferred | What did not transfer |",
        "|---|---|",
        *(f"| {a} | {b} |" for a, b in zip(transferred, missed, strict=True)),
        "",
        "**Engineering conclusion.** A deferral threshold has to be calibrated on labelled data "
        "that represents the traffic it will see. A benchmark's validation split is not a risk "
        "guarantee for production.",
    ]


def call_counts(rate: dict, n: int) -> str:
    """Per-seed Haiku calls as absolute numbers, e.g. ``170, 9, 31 of 5,500``."""
    return ", ".join(f"{round(v * n):,}" for v in rate["values"]) + f" of {n:,}"


def hybrid_reading(r: Results) -> list[str]:
    main = r.group("modernbert/k100")["final"]
    hybrid = r.hybrid("modernbert/k100")["test"]
    calls = call_counts(hybrid["llm_call_rate"], r.test_n)
    return [
        "**How to read the hybrid.** With few labels the fallback is worth the most: at k=10 it "
        "is the best evidence for the cascade (numbers above). With enough labels the local model "
        f"covers almost all traffic: at k=100 the hybrid sends {pm(hybrid['llm_call_rate'])}% of "
        f"test queries to Haiku ({calls} for seeds 42, 43, 44) and moves 8-way "
        f"accuracy from {pm(main['small_only']['accuracy_8'])}% to {pm(hybrid['accuracy_8'])}%. "
        "There the fallback is a small safety and diagnostic lever, not the main source of "
        "accuracy.",
    ]


def router_row(label: str, metrics: dict, llm: str | None = None) -> str:
    misroute = metrics["high_conf_oos_misroute_rate"]
    cells = [
        pm(metrics["accuracy_8"]),
        pm(metrics["oos_recall"]),
        "n/a" if misroute is None else pm(misroute),
        pm(metrics["llm_call_rate"]),
        llm if llm is not None else pm(metrics["llm_cost_usd_per_1k"], 3, 1.0),
    ]
    return f"| {label} | " + " | ".join(cells) + " |"


def routers_table(r: Results) -> list[str]:
    haiku = r.summary["llm_only_test"]
    rows = [
        "| router | 8-way acc (%) | OOS recall (%) | high-confidence OOS misroute (%) "
        "| Haiku calls (%) | Haiku US$ per 1K queries |",
        "|---|---|---|---|---|---|",
        f"| LLM-only (Haiku 4.5) | {pct(haiku['accuracy_8'])} | {pct(haiku['oos']['recall'])} "
        f"| n/a | 100.0 | {haiku['llm_cost_usd_per_1k']:.3f} |",
    ]
    for k in (10, 100):
        final = r.group(f"modernbert/k{k}")["final"]
        rows += [
            router_row(f"ModernBERT k={k}, small-only", final["small_only"]),
            router_row(
                f"ModernBERT k={k}, hybrid (target {pct(float(TARGET), 0)}%)",
                r.hybrid(f"modernbert/k{k}")["test"],
            ),
            router_row(f"ModernBERT k={k}, oracle (upper bound)", final["oracle"]),
        ]
    return rows


def efficiency_cells(r: Results, model: str) -> list[str]:
    result = r.group(f"{model}/k100")
    runs = r.k100_training[model]
    seconds = [b["train_wall_seconds"] for b in runs]
    memory = [b["peak_memory"]["driver_allocated_bytes"] / 2**30 for b in runs]
    ece = result["calibration"]["test_ece"]
    latency = r.cpu["models"][model]["end_to_end"]
    return [
        f"{runs[0]['parameters']['total'] / 1e6:.1f}M",
        f"{stat_line(seconds, 0)} s",
        f"{stat_line(memory, 2)} GiB",
        pm(result["final"]["small_only"]["accuracy_8"]),
        pm(result["final"]["small_only"]["oos_recall"]),
        f"{pm(ece['uncalibrated']['ece_151'], 2)} → {pm(ece['calibrated']['ece_151'], 2)}",
        f"{latency['p50_ms']:.1f} / {latency['p95_ms']:.1f} ms",
    ]


def stat_line(values: list[float], digits: int) -> str:
    n = len(values)
    mean = sum(values) / n
    std = (sum((v - mean) ** 2 for v in values) / (n - 1)) ** 0.5
    return f"{mean:,.{digits}f} ± {std:,.{digits}f}"


def efficiency_table(r: Results) -> list[str]:
    bert, modern = efficiency_cells(r, "bert"), efficiency_cells(r, "modernbert")
    haiku = r.summary["llm_only_test"]
    lat = r.haiku_latency["splits"]["test"]
    haiku_cells = [
        "n/a",
        "none (zero-shot)",
        "n/a",
        pct(haiku["accuracy_8"]),
        pct(haiku["oos"]["recall"]),
        "n/a",
        f"{lat['p50_ms']:.0f} / {lat['p95_ms']:.0f} ms (API, incl. network)",
    ]
    names = (
        "parameters",
        "training time, k=100 (Apple M4, MPS)",
        "training peak memory, k=100 (MPS driver, sampled)",
        "8-way accuracy, test (%)",
        "OOS recall, test (%)",
        "ECE 151-way, test, before → after temperature (%)",
        "latency p50 / p95, batch 1",
    )
    cpu = r.cpu
    return [
        "| | BERT-base (historical baseline) | ModernBERT-base (main model) | Claude Haiku 4.5 |",
        "|---|---|---|---|",
        *(
            f"| {n} | {a} | {b} | {c} |"
            for n, a, b, c in zip(names, bert, modern, haiku_cells, strict=True)
        ),
        "",
        f"Encoder latency: {cpu['hardware']['cpu']} CPU, batch 1, "
        f"{cpu['method']['intra_op_threads']} threads, torch {cpu['versions']['torch']}, "
        f"`torch.inference_mode()`, {cpu['method']['warmup_queries']} warm-up queries, then "
        f"{cpu['method']['queries']}; tokenization + forward + argmax. It is timed with the "
        "same architecture, not the fine-tuned weights (deleted to save disk): the pinned "
        "pretrained backbone, a 151-way head, the same tokenizer and max_length. Latency "
        "depends on shapes, not weight values. The timed model is built by the training loader "
        "with the model revision, max_length and torch and transformers versions of the trained "
        "run, and its parameter count equals the trained run's."
        f" Haiku: client-side time per call on the {lat['n']:,} test queries, including "
        "the network round trip, with up to 6 calls in flight; it is not a like-for-like "
        "comparison with the encoders (different machine, a network in between). Peak memory "
        "samples "
        "`torch.mps.driver_allocated_memory()` after each backward pass and optimizer step "
        "(includes the allocator cache). Accuracy and OOS recall use the 8-way aggregation "
        "chosen on validation; ECE is over the 151 intents. Values are mean ± std over seeds "
        "42, 43, 44.",
    ]


def cost_lines(r: Results) -> list[str]:
    measured = r.cost["measured"]
    rows = [x for x in r.cost["break_even"]["rows"] if x["label_usd_per_example"] == 0.0]
    prices = r.cost["assumptions"]["accelerator_usd_per_hour"]
    out = [
        f"Measured: Haiku costs {usd(measured['haiku']['cost_usd_per_1k_queries']['test'])} per "
        f"1K test queries ({measured['haiku']['input_tokens_per_1k_queries'] / 1000:,.1f}K input "
        f"and {measured['haiku']['output_tokens_per_1k_queries'] / 1000:,.2f}K output tokens per "
        f"1K; the whole run of {measured['haiku']['calls']:,} calls cost "
        f"{usd(measured['haiku']['cost_usd'], 2)}). One ModernBERT training run takes "
        f"{measured['training']['modernbert']['10']['train_wall_seconds']['mean'] / 60:.1f} min "
        f"at k=10 and "
        f"{measured['training']['modernbert']['100']['train_wall_seconds']['mean'] / 60:.1f} min "
        "at k=100 on an Apple M4.",
        "",
        "Break-even queries against LLM-only, for **assumed** accelerator prices (training only, "
        "no labelling cost, local inference priced as below). A scenario sensitivity, not "
        "a forecast:",
        "",
        "| point | router | " + " | ".join(f"at US${p:g}/h" for p in prices) + " |",
        "|---|---|" + "---|" * len(prices),
    ]
    for point, router in dict.fromkeys((x["point"], x["router"]) for x in rows):
        cells = [
            queries(x["break_even_queries"])
            for x in rows
            if (x["point"], x["router"]) == (point, router)
        ]
        name = point.replace("modernbert/", "ModernBERT ").replace("k", "k=")
        out.append(f"| {name} | {router.replace('_', '-')} | " + " | ".join(cells) + " |")
    return out + label_lines(r)


def more_or_less(value: float, reference: float) -> str:
    """How ``value`` compares with ``reference``, as a phrase that ends before the reference."""
    if value == reference:
        return "as accurate as"
    return "more accurate than" if value > reference else "less accurate than"


def label_lines(r: Results) -> list[str]:
    assumptions = r.cost["assumptions"]
    middle = assumptions["accelerator_usd_per_hour"][1]
    labels = assumptions["label_usd_per_example"]
    rows = [
        x
        for x in r.cost["break_even"]["rows"]
        if x["router"] == "hybrid" and x["accelerator_usd_per_hour"] == middle
    ]
    table = [
        f"| hybrid, US${middle:g}/h | labelled rows | "
        + " | ".join(f"at US${p:g} per label" for p in labels)
        + " |",
        "|---|---|" + "---|" * len(labels),
    ]
    for point in dict.fromkeys(x["point"] for x in rows):
        model, k = point.split("/")
        cells = [
            queries(x["break_even_queries"])
            for x in rows
            if x["point"] == point and x["label_usd_per_example"] > 0
        ]
        n = r.cost["measured"]["training"][model][k[1:]]["train_rows"]
        table.append(
            f"| {MODEL_LABEL[model]} {k.replace('k', 'k=')} | {n:,} | " + " | ".join(cells) + " |"
        )
    haiku = r.summary["llm_only_test"]["accuracy_8"]
    k10 = r.group("modernbert/k10")["final"]
    k10_small = more_or_less(k10["small_only"]["accuracy_8"]["mean"], haiku)
    k10_hybrid = more_or_less(r.hybrid("modernbert/k10")["test"]["accuracy_8"]["mean"], haiku)
    return [
        "",
        f"Break-even compares cost only: at k=10 the small model alone is {k10_small} Haiku "
        f"and the hybrid is {k10_hybrid} Haiku (router table).",
        "",
        "Training compute costs cents; labelling dominates once it has to be paid for. CLINC150 "
        "is an existing dataset, so labelling cost is an assumed sensitivity only (break-even "
        "queries, training plus labelling):",
        "",
        *table,
        "",
        f"Local inference is assumed to cost US${assumptions['vcpu_usd_per_hour']:g} per "
        "vCPU-hour at full utilisation, times the measured p50 latency and thread count. "
        "Full grid and every input: `results/cost/cost.json`.",
    ]


def aggregation_line(r: Results) -> list[str]:
    parts = []
    for model, label in MODEL_LABEL.items():
        picks = []
        for k in (1, 5, 10, 25, 50, 100):
            chosen = r.group(f"{model}/k{k}")["selected_aggregation"]
            text = chosen if isinstance(chosen, str) else f"per seed {'/'.join(chosen)}"
            picks.append(f"k={k} {text}")
        parts.append(f"{label}: " + ", ".join(picks))
    return [
        "**8-way aggregation.** The model predicts 151 intents. Two ways map that to 8 agents: "
        "take the argmax intent and map it (`argmax`), or sum the probabilities per agent and "
        "take the largest (`summed`). Each run picks one by validation 8-way accuracy only "
        "(ties go to argmax). " + ". ".join(parts) + ".",
    ]


def limitations(r: Results) -> list[str]:
    lr, steps = r.pilots["lr"], r.pilots["steps"]
    chosen_lr = {r.indexes[m]["learning_rate"] for m in MODEL_LABEL}
    s_min = {r.indexes[m]["min_train_steps"] for m in MODEL_LABEL}
    budget = sorted(
        {
            p["k"]
            for m in MODEL_LABEL
            for p in r.indexes[m]["points"]
            if p["decided_by"] == "min_train_steps"
        }
    )
    at_top = [
        f"learning rate {'/'.join(f'{v:g}' for v in sorted(chosen_lr))} is the top of "
        f"{{{', '.join(f'{v:g}' for v in lr['grid'])}}}"
        if max(chosen_lr) == max(lr["grid"])
        else "",
        f"S_min {'/'.join(str(v) for v in sorted(s_min))} is the top of "
        f"{{{', '.join(str(v) for v in steps['grid'])}}}"
        if max(s_min) == max(steps["grid"])
        else "",
    ]
    return [
        "## Limitations",
        "",
        "- **Hyperparameters at the edge of their grids.** The validation pilots chose values at "
        f"the upper end: {'; '.join(t for t in at_top if t)}. A better value may lie beyond.",
        f"- **Small k is a fixed step budget.** k in {{{', '.join(map(str, budget))}}} trains for "
        f"S_min = {max(s_min)} steps (more than 5 epochs), so those points show performance at "
        "that budget.",
        "- **Latency uses the same architecture, not the trained weights** (see the efficiency "
        "table note).",
        "- **Validation thresholds do not transfer** to test (headline above).",
        "- **One benchmark.** CLINC150, English, one domain mix; BANKING77-OOS is planned for "
        "v0.2.",
        "- Training on Apple MPS is not bit-for-bit deterministic, hence three seeds.",
    ]


def figure_lines() -> list[str]:
    lines: list[str] = []
    for name, alt, caption in FIGURES:
        lines += [f"![{alt}](results/figures/{name})", "", f"*{caption}*", ""]
    return lines[:-1]


def readme_block(r: Results) -> str:
    sections = [
        headline(r),
        hybrid_reading(r),
        ["### Routers (test, 8-way)", "", *routers_table(r)],
        ["### Efficiency (AC5)", "", *efficiency_table(r)],
        ["### Cost (RQ5)", "", *cost_lines(r)],
        aggregation_line(r),
        ["### Figures", "", *figure_lines()],
        limitations(r),
    ]
    body = "\n\n".join("\n".join(s) for s in sections)
    return f"{BEGIN}\n{body}\n{END}"


def curve_table(r: Results) -> list[str]:
    rows = [
        "| model | k | 8-way acc (%) | OOS recall (%) | hybrid acc (%) | hybrid Haiku calls (%) |",
        "|---|---|---|---|---|---|",
    ]
    for model in ("modernbert", "bert", "tfidf-centroid", "majority"):
        for k in (1, 5, 10, 25, 50, 100):
            final = r.group(f"{model}/k{k}")["final"]
            hybrid = final["fallback"][TARGET]["hybrid"]
            tail = (
                ("n/a", "n/a")
                if hybrid is None
                else (pm(hybrid["test"]["accuracy_8"]), pm(hybrid["test"]["llm_call_rate"]))
            )
            rows.append(
                f"| {model} | {k} | {pm(final['small_only']['accuracy_8'])} | "
                f"{pm(final['small_only']['oos_recall'])} | {tail[0]} | {tail[1]} |"
            )
    return rows


def report_md(r: Results) -> str:
    block = readme_block(r).replace("](results/figures/", "](figures/")
    parts = [
        "# TinyRouter results",
        "",
        "Generated by `make report` from `results/*.json`. Do not edit by hand.",
        "",
        block,
        "",
        f"## Learning curves (test, target {pct(float(TARGET), 0)}% for the hybrid)",
        "",
        *curve_table(r),
    ]
    return "\n".join(parts) + "\n"


def replace_block(readme: str, block: str) -> str:
    start, end = readme.find(BEGIN), readme.find(END)
    if start < 0 or end < start:
        raise ValueError("README.md has no generated block (BEGIN ... END markers)")
    return readme[:start] + block + readme[end + len(END) :]


def outputs(root: Path, repo: Path, readme_out: Path | None = None) -> dict[Path, str]:
    """report.md and the README with its block rebuilt; ``readme_out`` keeps repo/README.md as is.

    ``make reproduce`` passes ``readme_out`` so a rerun writes its README next
    to its own results instead of over the committed one.
    """
    r = Results.load(root)
    readme = repo / "README.md"
    return {
        root / "report.md": report_md(r),
        readme_out or readme: replace_block(readme.read_text(encoding="utf-8"), readme_block(r)),
    }


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--results-dir", default="results")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--check", action="store_true", help="compare only; exit 1 if stale")
    parser.add_argument("--readme-out", default=None, help="write the README here, not in --repo")
    args = parser.parse_args(argv)
    stale = []
    readme_out = Path(args.readme_out) if args.readme_out else None
    moved = Path(args.results_dir).resolve() != (Path(args.repo) / "results").resolve()
    if moved and readme_out is None and not args.check:
        parser.error(
            "--results-dir is not <repo>/results; pass --readme-out too, or the committed "
            "README would be rewritten from other results"
        )
    for path, text in outputs(Path(args.results_dir), Path(args.repo), readme_out).items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if args.check:
            if current != text:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path}")
    if stale:
        print(f"stale, run `make report`: {', '.join(stale)}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
